/**
 * Created by gromi on 3/26/2017.
 */
var GATEWAY_URLS = {
    SAVE_PERIOD: BASE_URL + 'reservation-period/save-period',
    SAVE_PERIODS: BASE_URL + 'reservation-period/save-periods',
    BUY_CONSTRUCTION: BASE_URL + 'construction/buy-construction',
    BUY_CONSTRUCTIONS: BASE_URL + 'construction/buy-constructions',
    RESERV_CONSTRUCTION: BASE_URL + 'construction/reserv-construction',
    RESERV_CONSTRUCTIONS: BASE_URL + 'construction/reserv-constructions',
    NOTIFICATION_CREATE: BASE_URL + 'construction/notification-create',
    GET_DOCUMENTS_CALENDAR: BASE_URL + 'documents/get-documents-calendar',
    GET_DOCUMENTS: BASE_URL + 'documents/get-documents',
    GET_CONTRACTS: BASE_URL + 'documents/get-contracts',
    GET_SUBCLIENT_DOCUMENTS_CALENDAR: BASE_URL + 'documents/get-subclient-documents-calendar',
    DELETE_DOCUMENT: BASE_URL + 'documents/delete-document',
    DELETE_CONTRACT: BASE_URL + 'documents/delete-contract',
    DELETE_SUBCLIENT: BASE_URL + 'documents/delete-subclient',
    UPDATE_TERM_PAYMENT: BASE_URL + 'documents/update-term-payment',
    DELETE_CONSTRUCTION_IMAGE: BASE_URL + 'admin/construction/delete-image',
    DELETE_SHOPPING_CART_ITEM: BASE_URL + 'shopping-cart/delete',
    GET_CONSTRUCTION_RESERVATIONS: BASE_URL + 'construction/get-construction-reservations',
    VALIDATE_CONSTRUCTION_DATE_RANGE: BASE_URL + 'construction/validate-and-save-construction-date-range',
    CHECKOUT: BASE_URL + 'shopping-cart/checkout',
    APPROVE_ORDER: BASE_URL + 'clients/approve-order',
    BUY_RESERVED_CONSTRUCTION: BASE_URL + 'orders/buy-reserved-construction',
    GET_REPORT: BASE_URL + 'reports/download',
    DELETE_ORDER: BASE_URL + 'clients/delete-order',
    UPDATE_THEMATIC: BASE_URL + 'orders/update-thematic',
};